### ISSUE TITLE
Confusing error message about tuned profiles when running role

### ISSUE THREAD

**Issue by dpredhat** [linux-system-roles/mssql#24]
TASK [microsoft.sql.server : Add mssql to the list of Tuned profiles] ****************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["tuned-adm", "profile", "virtual-guest", "mssql"], "delta": "0:00:00.142634", "end": "2021-06-29 16:51:29.639275", "msg": "non-zero return code", "rc": 1, "start": "2021-06-29 16:51:29.496641", "stderr": "Cannot load profile(s) 'virtual-guest mssql': Cannot find profile 'throughput-performance' in '['/etc/tuned', '/usr/lib/tuned']'.", "stderr_lines": ["Cannot load profile(s) 'virtual-guest mssql': Cannot find profile 'throughput-performance' in '['/etc/tuned', '/usr/lib/tuned']'."], "stdout": "", "stdout_lines": []}

- The package is tuned-profiles-mssql
- The tuned profile is called mssql

**Comment by richm** [comment]
What version of the role are you using?  What version of ansible are you using?  What is the platform for your control host?  What is the platform for your managed host?  I guess since you are using `[localhost]` that your control host is the same as your managed host?

**Comment by dpredhat** [comment]
Hi Rich - Trying to use it in our lab here - https://lab.redhat.com/sql-server-ansible.

Pulling down the latest microsoft.sql:1.0.11

**Comment by richm** [comment]
Ok - I'm assuming you are on a rhel8 system and are running the role against locahost?  e.g. ansible-playbook -c local ... ?

**Comment by dpredhat** [comment]
Yes, using RHEL 8.4, and running the role against local host. 

Feel free to check out the lab link above to debug/investigate this issue further.

**Comment by richm** [comment]
ok - tried the lab link - looks like it gets past this point and hits another error - would need to "clean" the system to try it again, or spin up a new machine

What should happen is that you will get the error - but - the code should rescue the error and continue  https://github.com/linux-system-roles/mssql/blob/master/tasks/main.yml#L121 - it looks like that is what it did because if I look at /usr/lib/tuned/mssql/tuned.conf it has been fixed

So is it possible that the playbook failed, and you scanned the output, and this was the first error you found, but there were subsequent tasks after this failure, and the actual failure was further down in the output?

**Comment by richm** [comment]
@spetrosi we should figure out a way to either suppress the error so that the task does not print `fatal` and `FAILED!`, or change the error message to better explain what is happening.

**Comment by spetrosi** [comment]
I remember @djez complained about roles having the rescue blocks. IIRC these expected errors caused tests to fail, and overall might be confusing for users because they see errors in the output and might think that they need to troubleshoot them. Should I better remove the rescue block completely and perform the check in some other way?
