### ISSUE TITLE
the output has been hidden due to the fact that 'no_log: true' was specified for this result

### ISSUE THREAD

**Issue by phillipyeo** [linux-system-roles/mssql#240]
Encountered error while running playbook on TASK [microsoft.sql.server : Gather package facts]
Error msg: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

Need help on this!

**Comment by spetrosi** [comment]
Hello,

As a workaround, you can remove `no_log: true` from the role tasks file to see the output. In the role's directory, open `tasks/main.yml` with your text editor, find tasks with that use the module `package_facts`, and remove `no_log: true` from each task (there are 4 tasks with such a name).

And for the role, I think it's the best to remove `no_log: true` from these tasks, this is a valid issue. I added it there in the first place to clear the output of the role when I run it with `-v` because `package_facts` returns a large output that messes the logs.

**Comment by phillipyeo** [comment]
Hi Spetrosi,

I've managed to remove no_log: true and the error showed no python interpreters found in my targeted machine.
Thanks a lot for your help. :)
